# Configuration file for ansible-lint

#  -------------------------------------------------------------------------------------------------
#  Unused configuration parameters

# One or more files or paths. When missing it will enable auto-detection mode
# playbook: []

# Only check rules whose id/tags do not match these values
skip_list:
  - package-latest   # Package installs should not use latest

# Only warn about these rules
# warn_list: []

# Path to directories or files to skip
# exclude_paths: []

# Specify custom rule directories.
# rulesdir: []
# Keep default rules when using rulesdir
# use_default_rules: false

# only check rules whose id/tags match these values
# tags: []

# Display path relative to CWD
# XXX Seems to not be functional :'(
# display_relative_path: true


#  -------------------------------------------------------------------------------------------------
#  Useless configuration parameters

# parseable output in the format of pep8
# parseable: false
# parseable output including severity of rule with pep8 format
# parseable-severity: false

# Disable colored output
# nocolor: false
# Try force colored output (relying on ansible's code)
# force-color: false

# Format used rules output: rich, plain, rst
# format: rich

# list all the tag
# listtags: false

# define verbosity level
# verbosity: 0

# quieter, although not silent output
# quiet: false

# list all the rules
# listrules: false
