# Copyright 2022 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
repos:
  - repo: local
    hooks:
      - id: addlicense
        name: addlicense
        entry: tools/autodoc/addlicense.sh
        language: script
        types: ['text']
        exclude: ^(\.terraform\/.*$|\..*|README.md)
        exclude_types: ['json']
        pass_filenames: true
        require_serial: true
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_validate
  - repo: local
    hooks:
      - id: terraform-readme
        name: terraform-readme
        entry: tools/autodoc/terraform_docs.sh
        language: script
        types: ['terraform']
        exclude: \.terraform\/.*$
        pass_filenames: true
        require_serial: true
