# Ansible scripts for deploying a DAOS client node
# yamllint disable rule:line-length

- name: Gather distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ playbook_dir }}/vars/{{ ansible_distribution | replace(' ', '_') }}{{ ansible_distribution_major_version }}.yml"

- name: Copy bash script setup-client_entries.sh
  become: true
  copy:
    src: file/setup-client_entries.sh
    dest: /root/setup-client_entries.sh
    owner: root
    group: root
    mode: '0600'

- name: Create DAOS Client entries
  become: true
  command: /bin/bash /root/setup-client_entries.sh

- name: Update systemd service for DAOS agent
  become: true
  template:
    src: daos_agent.service.j2
    dest: /usr/lib/systemd/system/daos_agent.service
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Create base agent configuration file tree
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/daos
    - /etc/daos/certs

- name: Install DAOS client dependency packages
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | replace(' ', '_') }}{{ ansible_distribution_major_version}}/clients_dependencies.yml"

- name: Update dynamic linker configuration
  become: true
  template:
    src: templates/daos-ld.so.conf.j2
    dest: /etc/ld.so.conf.d/daos-ftest-x86_64.conf
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Update search path commands
  become: true
  lineinfile:
    path: /etc/security/pam_env.conf
    state: present
    regexp: '^PATH='
    line: "PATH={{ daos_runtime_dir }}/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/bin/syscfg:/root/bin"
    backup: true

- name: Create MPI module directory
  become: true
  file:
    path: /etc/modulefiles/mpi
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: true
