# Ansible scripts for configuring a DAOS node with ftest

- name: Add CodeReady Linux Builder repository
  become: true
  community.general.dnf_config_manager:
    name: crb
    state: enabled
  ignore_errors: true

- name: Add EPEL release
  become: true
  dnf:
    name: epel-release
    state: present

- name: Install rpms DAOS base dependencies
  become: true
  dnf:
    state: latest
    update_cache: true
    name: "{{ daos_base_deps.rpms }}"
