# For a single-server system

name: daos_server
access_points: ['localhost']
provider: ofi+tcp
control_log_file: /tmp/daos_server.log
transport_config:
   allow_insecure: true

telemetry_port: 9191

engines:
-
  targets: 1
  first_core: 0
  nr_xs_helpers: 0
  fabric_iface: eth0
  fabric_iface_port: 31416
  log_file: /tmp/daos_engine.0.log

  env_vars:
  - FI_SOCKETS_MAX_CONN_RETRY=1
  - FI_SOCKETS_CONN_TIMEOUT=2000

  # Storage definitions (one per tier)
  storage:
    -
      # When scm_class is set to ram, tmpfs will be used to emulate SCM.
      # The size of ram is specified by scm_size in GB units.
      class: ram
      scm_size: 8
      scm_mount: /mnt/daos
    -
      # When bdev_class is set to file, Linux AIO will be used to emulate NVMe.
      # The size of file that will be created is specified by bdev_size in GB units.
      # The location of the files that will be created is specified in bdev_list.
      class: file
      bdev_size: 16
      bdev_list: [/tmp/daos-bdev]
