# Set of variables for Rocky 9
# yamllint disable rule:line-length

daos_base_deps:
  rpms:
    - bash
    - bzip2-devel
    - capstone
    - createrepo
    - dnf-plugins-core
    - environment-modules
    - gdb
    - glibc
    - iproute
    - jq
    - lbzip2
    - libasan
    - numactl
    - numactl-libs
    - numatop
    - platform-python
    - psmisc
    - python3
    - python3-devel
    - python3-pexpect
    - python3-wheel
    - systemd
    - tree
    - valgrind-devel
    - wget

daos_dev_deps:
  rpms:
    - bear
    - daxctl-devel
    - gcc-gfortran
    - libaec-devel
    - libattr-devel
    - ndctl-devel
    - python3.11
    - python3.11-devel
    - python3-clustershell
    - python3-dnf
    - python3-pip
    - rpmdevtools
    - rpm-build

daos_client_deps:
  rpms:
    - hwloc
    - fuse3
    - fuse3-libs
    - libaec
    - libuuid
    - lz4-libs
    - numactl-devel
    - systemd
    - util-linux

daos_server_deps:
  rpms:
    - hwloc
    - ipmctl
    - libipmctl
    - libpmemobj
    - libuuid
    - lz4-libs
    - ndctl
    - pciutils

mlnx_deps:
  rpms:
    - mlnx-ofed-all
