extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'

# ignore:

rules:
  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 2
    level: warning
  comments-indentation:
    level: warning
  document-end:
    present: false
  document-start:
    present: true
    level: warning
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
    level: warning
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file:
    level: warning
  new-lines:
    type: unix
  octal-values: disable
  quoted-strings:
    quote-type: any
    required: false
    extra-required: []
    extra-allowed: []
  trailing-spaces: enable
  truthy:
    allowed-values: ['true', 'false']
