name: Create Release
# This workflow is triggered on pushes to the master branch of the repository.
on:
  push:
    paths:
      - TAG
    branches:
      - master
      - 'release/**'

permissions: {}

jobs:
  make_release:
    name: Create Release
    if: github.repository == 'daos-stack/daos'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 2
      - uses: ./.github/actions/make_release
        id: make_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
