name: Create Release
# This workflow is triggered on pushes to the master branch of the repository.
on:
  push:
    paths:
      - TAG
    branches:
      - master
      - 'release/**'

jobs:
  make_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/make_release
        id: make_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
