name: Create Release
# This workflow is triggered on pushes to the master branch of the repository.
on:
  push:
    paths:
      - TAG
    branches:
      - master
      - 'release/**'

permissions: {}

jobs:
  make_release:
    name: Create Release
    if: github.repository == 'daos-stack/daos'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
      - uses: ./.github/actions/make_release
        id: make_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
