name: Pylint

# Always run on Pull Requests as then this check can be marked as required.  It takes less than
# two minutes to run and we can probably decrease this over time.

# This check runs on PRs using a defined pylint version (from utils/cq/requirements.txt) but on
# landings using the latest version.  Landings builds also trigger a check to see if
# a newer version is available.
on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'release/*'
  pull_request:

jobs:
  pylint:
    name: Pylint check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install core python packages
        run: python3 -m pip install --requirement requirements.txt
      - name: Install extra python packages
        run: python3 -m pip install --requirement utils/cq/requirements.txt
      - name: Upgrade pylint
        if: ${{ github.event_name != 'pull_request' }}
        run: pip install --upgrade pylint
      - name: Install enchant
        run: sudo apt-get update && sudo apt-get -y install python3-enchant
      - name: Run pylint check.
        run: ./utils/cq/daos_pylint.py --git --output-format github

  upgrade-check:
    name: Check for newer pylint version
    runs-on: ubuntu-22.04
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install extra python packages
        run: python3 -m pip install --requirement utils/cq/requirements.txt
      - name: Check pylint version
        run: pylint --version | tee -a pylint-pre
      - name: Upgrade
        run: pip install --upgrade pylint
      - name: Check pylint version
        run: pylint --version | tee -a pylint-post
      - name: Check for upgrades
        run: diff pylint-pre pylint-post
