name: Unit testing

on:
  pull_request:

permissions: {}

jobs:
  Run_in_docker:
    if: github.repository == 'daos-stack/daos'
    runs-on: [self-hosted, docker]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build deps in Docker
        run: docker build . --file utils/docker/Dockerfile.el.9
            --build-arg DAOS_BUILD=no
            --build-arg DEPS_JOBS=50
      - name: Build daos in Docker
        run: docker build . --file utils/docker/Dockerfile.el.9
            --build-arg DEPS_JOBS=50
            --build-arg DAOS_KEEP_SRC=yes
            --build-arg DAOS_TARGET_TYPE=debug
            --build-arg DAOS_JAVA_BUILD=yes
            --tag gha-amd-${{github.run_id}}-${{github.run_attempt}}
      - name: Run Unit-Testing1
        run: docker run gha-amd-${{github.run_id}}-${{github.run_attempt}}
            ./daos/utils/ci/run_unit_tests_in_gha.sh
